name: Build Python Distribution

on: push

jobs:
  build_wheels:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: python3 -m pip install build --user
    - name: Build binary wheel and source tarball
      run: python3 -m build
    - name: Store the distribution artifacts
      uses: actions/upload-artifact@v3
      with:
        name: oscr-wheel
        path: dist/

  build_binary:
    name: Build binary ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: python3 -m pip install nuitka --user
    - name: Install requirements
      run: python3 -m pip install -r requirements.txt
    - name: Build the binary
      run: python -m nuitka --standalone --enable-plugin=pyqt6 --static-libpython=yes --onefile --output-filename=OSCR --output-dir=oscr.dist main.py
    - name: Store the nuikta artifacts
      uses: actions/upload-artifact@v3
      with:
        name: oscr-${{ matrix.os }}-${{ strategy.job-index }}
        path: oscr.dist/
