name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: >-
        python3 -m pip install build nuitka --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Build a the standalone application
      run: python -m nuitka --standalone --enable-plugin=pyside6 main.py
    - name: Store the distribution artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Store the nuikta artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: main.dist/
